if $programname == 'nasnotify' then {
    action(type="omfile"
           file="/var/ugreen/log/nasnotify.slog"
           template="UgLogFormat"
           fileCreateMode="0600"
           dirCreateMode="0755"
           createDirs="on")
    stop
}
