location ~ ^/(?:nasnotify|com\.autunn\.nasnotifyfresh)(?:/|$) {
    proxy_set_header Host $http_host;
    proxy_set_header Port $server_port;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Real-Port $server_port;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Original-URI $request_uri;
    proxy_intercept_errors on;
    proxy_read_timeout 300;
    proxy_pass http://unix:/var/packages/com.autunn.nasnotifyfresh/data/run/nasnotify.sock;
    proxy_http_version 1.1;
    proxy_set_header Connection "";
}

location ~ ^/ugreen/v[0-9]/(?:nasnotify|com\.autunn\.nasnotifyfresh)(?:/|$) {
    proxy_set_header Host $http_host;
    proxy_set_header Port $server_port;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Real-Port $server_port;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Original-URI $request_uri;
    proxy_intercept_errors on;
    proxy_read_timeout 300;
    proxy_pass http://unix:/var/packages/com.autunn.nasnotifyfresh/data/run/nasnotify.sock;
    proxy_http_version 1.1;
    proxy_set_header Connection "";
}
